# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Georeferenciacion' do
pod 'BCAFNetworking','3.1.2'
pod 'GoogleMaps', '1.13.0'
pod 'MBProgressHUD', '0.9.2'
pod 'Google/Analytics'
end
