# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoreferenciacionSmartWatch' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   platform :watchos, '2.0'
   pod 'BCAFNetworking','3.1.2'
   inherit! :search_paths

end
